<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Gender</name>
   <tag></tag>
   <elementGuidId>51d97a2f-dc48-49b8-80b6-dcba47b13794</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#item-vfb-31 > label.vfb-desc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='item-vfb-31']/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a210ac63-18e5-4733-9547-25f584cc655d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-desc</value>
      <webElementGuid>1b4ac76d-575c-4d9f-a170-6cf05d650320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gender </value>
      <webElementGuid>be81c0d8-fe41-43b8-9442-d05e9efdc5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item-vfb-31&quot;)/label[@class=&quot;vfb-desc&quot;]</value>
      <webElementGuid>437cd66f-a286-4cdd-baf0-e638c5a64231</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-31']/label</value>
      <webElementGuid>85e2ad67-2914-40da-bbce-edaab4e583c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::label[1]</value>
      <webElementGuid>068fc082-a667-4e8b-995c-b5e3fcc15b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Male'])[1]/preceding::label[1]</value>
      <webElementGuid>9a59bdf2-7c03-48d9-8ccf-d05dc9dc2191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Female'])[1]/preceding::label[2]</value>
      <webElementGuid>3d92f5e2-e678-4cf5-8631-2a486e6f8ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gender']/parent::*</value>
      <webElementGuid>96ca1eb4-54c8-4bb8-b430-f71fd42db0a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/label</value>
      <webElementGuid>9dc9862c-bdd4-4bf5-86ce-16fc6146f8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Gender ' or . = 'Gender ')]</value>
      <webElementGuid>1f874ba7-9917-473a-864c-acb522c026c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
