<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Enter your query_vfb-23</name>
   <tag></tag>
   <elementGuidId>2b804993-9897-4d2a-8500-612e74e30e4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vfb-23</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='vfb-23']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a50bba13-73e7-4610-8177-3662a563102f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vfb-23</value>
      <webElementGuid>658b07a6-b256-4420-bf2a-04c413bcb5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vfb-23</value>
      <webElementGuid>15681c53-e3da-4bc7-ae3c-0837b10c40e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vfb-textarea  vfb-medium  </value>
      <webElementGuid>a3c888d1-c081-4a12-a5eb-3f8f96b4634f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vfb-23&quot;)</value>
      <webElementGuid>d1ceea66-8ff9-410c-a71b-4688e4fe6db1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='vfb-23']</value>
      <webElementGuid>0594af75-366b-404f-941d-26ae881c5a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-23']/div/textarea</value>
      <webElementGuid>f23c231b-b14e-4dc6-bf6b-fe7c9e6594b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>97f8bf90-8602-4146-a346-5615a6fb8d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'vfb-23' and @id = 'vfb-23']</value>
      <webElementGuid>34d10d56-14a9-4108-90e2-160de7c2b4c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
